/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.signUpLandingPage;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Container;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import property.backend.ecosystem.BankingOrganization;
import property.backend.ecosystem.Enterprise;
import property.backend.ecosystem.FinancialInstitutionEnterprise;
import property.backend.ecosystem.Organization;
import property.backend.ecosystem.PropertyManagementEnterprise;
import property.backend.ecosystem.RealEstateNetwork;
import property.backend.users.Bank;
import property.backend.users.UserAccount;
import property.backend.users.UserAuthentication;
import property.ui.bank.BankJPanel;

/**
 *
 * @author meghana
 */
public class BankWorkAreaJPanel extends javax.swing.JPanel {
     private RealEstateNetwork ecosystem;
    private UserAccount account;
    
     private Color highlightColor = new Color(181, 218, 255);

    /**
     * Creates new form BankWorkAreaJPanel
     */
    public BankWorkAreaJPanel(RealEstateNetwork ecosystem,UserAccount account) {
        this.ecosystem=ecosystem;
        this.account=account;
        initComponents();
        highlightButtons();
        
     //   loadBankDetails();
    }
    
     /**
     * Apply highlight color to all buttons in the panel
     */
    private void highlightButtons() {
        // Set the background color for the Add button
        btnAdd.setBackground(highlightColor);
        btnAdd.setOpaque(true);
        btnAdd.setBorderPainted(false);
    }
    
     private void loadBankDetails() {
         if (account.getRole() instanceof Bank) {
            Bank bank = (Bank) account.getRole();
            
            // Populate fields with existing data
            txtBank.setText(bank.getBankName());
            txtPhone.setText(bank.getPhoneNumber());
            txtAddress.setText(bank.getAddress());
        }
    }
     
     private void clearForm() {
        txtBank.setText("");
        txtPhone.setText("");
        txtAddress.setText("");
        txtBank.requestFocus();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBank = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtBank = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(181, 218, 255));

        lblBank.setText("Bank Name");

        lblPhone.setText("Phone Number");

        lblAddress.setText("Bank Address");

        txtBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBankActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("Bank Details");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/images.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(528, 528, 528))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBank, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPhone))
                                .addGap(224, 224, 224)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBank, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                                    .addComponent(txtPhone)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(310, 310, 310))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBank))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhone)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddress)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(btnAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(223, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBankActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String bankName = txtBank.getText().trim();
        String phoneNumber = txtPhone.getText().trim();
        String address = txtAddress.getText().trim();
        
        if (bankName.isEmpty() || phoneNumber.isEmpty() || address.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please fill in all fields.",
                "Incomplete Information",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Validate phone number format (10 digits only)
        if (!isValidPhoneNumber(phoneNumber)) {
            JOptionPane.showMessageDialog(this,
                "Please enter a valid 10-digit phone number.",
                "Invalid Phone Number",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
          try {
            // Create a new bank entry instead of updating existing one
            createNewBankEntry(bankName, phoneNumber, address);
            
            JOptionPane.showMessageDialog(this,
                "Bank details added successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
            
            System.out.println("New bank added: " + bankName + ", " + phoneNumber + ", " + address);
            clearForm();
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Error adding bank details: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Validate phone number - must be 10 digits only
     */
    private boolean isValidPhoneNumber(String phoneNumber) {
        // Remove any non-digit characters
        String digitsOnly = phoneNumber.replaceAll("\\D", "");
        
        // Check if it's exactly 10 digits
        return digitsOnly.length() == 10;
    }
    
    private void createNewBankEntry(String bankName, String phoneNumber, String address) {
        // Create a new Bank role with the provided details
        Bank newBank = new Bank();
        newBank.setBankName(bankName);
        newBank.setPhoneNumber(phoneNumber);
        newBank.setAddress(address);
        
        // Create a unique username for this bank entry
        String uniqueUsername = "bank_" + System.currentTimeMillis();
        
        // Create new UserAccount using no-arg constructor
        UserAccount newBankAccount = new UserAccount();
        newBankAccount.setUsername(uniqueUsername);
        newBankAccount.setPassword("default123"); // Default password
        newBankAccount.setName(bankName);
        newBankAccount.setRole(newBank);
        
        // Find or create BankingOrganization
        BankingOrganization bankOrg = findOrCreateBankingOrganization();
        
        // Set the organization for the new account
        newBankAccount.setOrganization(bankOrg);
        
        // Add the new bank to the organization
        bankOrg.getUserAccountList().add(newBankAccount);
        
        // Add to UserAuthentication system
        UserAuthentication userAuth = UserAuthentication.getInstance();
        userAuth.getUserAccounts().add(newBankAccount);
        
        // Save changes to file
        saveChangesToFile();
        
        System.out.println("Created new bank entry with username: " + uniqueUsername);
    }
    
    private BankingOrganization findOrCreateBankingOrganization() {
        // Find existing BankingOrganization in FinancialInstitutionEnterprise
        for (Enterprise enterprise : ecosystem.getEnterpriseList()) {
            // Check FinancialInstitutionEnterprise first (where banks typically belong)
            if (enterprise instanceof FinancialInstitutionEnterprise) {
                for (Organization org : enterprise.getOrganizationList()) {
                    if (org instanceof BankingOrganization) {
                        System.out.println("Found existing BankingOrganization in FinancialInstitutionEnterprise");
                        return (BankingOrganization) org;
                    }
                }
            }
            // Also check PropertyManagementEnterprise as fallback
            else if (enterprise instanceof PropertyManagementEnterprise) {
                for (Organization org : enterprise.getOrganizationList()) {
                    if (org instanceof BankingOrganization) {
                        System.out.println("Found existing BankingOrganization in PropertyManagementEnterprise");
                        return (BankingOrganization) org;
                    }
                }
            }
        }
        
        // If no BankingOrganization found, create one in FinancialInstitutionEnterprise
        FinancialInstitutionEnterprise financialEnterprise = null;
        for (Enterprise enterprise : ecosystem.getEnterpriseList()) {
            if (enterprise instanceof FinancialInstitutionEnterprise) {
                financialEnterprise = (FinancialInstitutionEnterprise) enterprise;
                break;
            }
        }
        
        // If no FinancialInstitutionEnterprise exists, create one
        if (financialEnterprise == null) {
            financialEnterprise = new FinancialInstitutionEnterprise("Financial Institution");
            ecosystem.addEnterprise(financialEnterprise);
            System.out.println("Created new FinancialInstitutionEnterprise");
        }
        
        // Create new BankingOrganization
        BankingOrganization newBankOrg = new BankingOrganization("Banking Organization", financialEnterprise);
        financialEnterprise.addOrganization(newBankOrg);
        System.out.println("Created new BankingOrganization in FinancialInstitutionEnterprise");
        
        return newBankOrg;
    }
    
    // Keep these methods for backward compatibility if needed
    private void updateUserAuthentication() {
        UserAuthentication userAuth = UserAuthentication.getInstance();
        
        // Find and update the user in UserAuthentication
        for (UserAccount user : userAuth.getUserAccounts()) {
            if (user.getUsername().equals(account.getUsername())) {
                user.setName(account.getName());
                user.setRole(account.getRole());
                break;
            }
        }
    }
    
    private void updateBankInEcosystem() {
        System.out.println("=== Starting updateBankInEcosystem ===");
        System.out.println("Looking for user: " + account.getUsername() + " (" + account.getName() + ")");
        
        boolean foundUser = false;
        
        // Find the bank in ALL enterprises (not just PropertyManagementEnterprise)
        for (Enterprise enterprise : ecosystem.getEnterpriseList()) {
            System.out.println("Checking enterprise: " + enterprise.getClass().getSimpleName() + " - " + enterprise.getName());
            
            for (Organization org : enterprise.getOrganizationList()) {
                System.out.println("Checking organization: " + org.getClass().getSimpleName() + " - " + org.getName());
                
                if (org instanceof BankingOrganization) {
                    BankingOrganization bankOrg = (BankingOrganization) org;
                    System.out.println("Found BankingOrganization with " + bankOrg.getUserAccountList().size() + " users");
                    
                    // Update the bank in the organization
                    for (UserAccount user : bankOrg.getUserAccountList()) {
                        System.out.println("Checking user in org: " + user.getUsername() + " (" + user.getName() + ")");
                        
                        if (user.getUsername().equals(account.getUsername())) {
                            System.out.println("Found matching user! Updating...");
                            user.setName(account.getName());
                            user.setRole(account.getRole());
                            foundUser = true;
                            System.out.println("Updated user: " + user.getName() + " with role: " + user.getRole().getClass().getSimpleName());
                            break;
                        }
                    }
                } else {
                    System.out.println("Organization " + org.getName() + " is not a BankingOrganization");
                }
            }
        }
        
        if (!foundUser) {
            System.out.println("WARNING: User " + account.getUsername() + " not found in any BankingOrganization!");
            System.out.println("This user might not be properly added to the ecosystem structure.");
        }
        
        System.out.println("=== Finished updateBankInEcosystem ===");
    }
    
    private void saveChangesToFile() {
        try {
            // Save ecosystem
            FileOutputStream fileOut = new FileOutputStream("ecosystem.ser");
            ObjectOutputStream out = new ObjectOutputStream(fileOut);
            out.writeObject(ecosystem);
            out.close();
            fileOut.close();
            
            // Save UserAuthentication
            UserAuthentication userAuth = UserAuthentication.getInstance();
            FileOutputStream userFileOut = new FileOutputStream("userauth.ser");
            ObjectOutputStream userOut = new ObjectOutputStream(userFileOut);
            userOut.writeObject(userAuth);
            userOut.close();
            userFileOut.close();
            
            System.out.println("Bank data saved successfully");
            
        } catch (IOException e) {
            e.printStackTrace();
            System.err.println("Error saving bank data: " + e.getMessage());
        }
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBank;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBank;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
