/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.signUpLandingPage;

import java.awt.Color;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import javax.swing.JOptionPane;
import property.backend.ecosystem.BuilderOrganization;
import property.backend.ecosystem.Enterprise;
import property.backend.ecosystem.Organization;
import property.backend.ecosystem.PropertyManagementEnterprise;
import property.backend.ecosystem.RealEstateNetwork;
import property.backend.users.Builder;
import property.backend.users.UserAccount;
import property.backend.users.UserAuthentication;

/**
 *
 * @author sruth
 */
public class BuilderWorkAreaJPanel extends javax.swing.JPanel {

    private RealEstateNetwork ecosystem;
    private UserAccount account;
     private Color highlightColor = new Color(181, 218, 255);
    /**
     * Creates new form BuilderWorkAreaJPanel
     */
    public BuilderWorkAreaJPanel(RealEstateNetwork ecosystem,UserAccount account) {
        this.ecosystem=ecosystem;
        this.account=account;
        initComponents();
        highlightButtons();
        
        //loadBuilderDetails();
    }
    
    /**
     * Apply highlight color to all buttons in the panel
     */
    private void highlightButtons() {
        // Set the background color for the Add button
        btnAdd.setBackground(highlightColor);
        btnAdd.setOpaque(true);
        btnAdd.setBorderPainted(false);
    }
    
//     private void loadBuilderDetails() {
//        if (account.getRole() instanceof Builder) {
//            Builder builder = (Builder) account.getRole();
//            
//            // Populate fields with existing data
//            txtBuilder.setText(builder.getBuilderName());
//            txtPhone.setText(builder.getPhoneNumber());
//            txtAddress.setText(builder.getAddress());
//        }
//    }
     // Method to clear all form fields
    private void clearForm() {
        txtBuilder.setText("");
        txtPhone.setText("");
        txtAddress.setText("");
        
        // Set focus back to the first field for easy data entry
        txtBuilder.requestFocus();
    }

     


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBuilder = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        txtBuilder = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(181, 218, 255));

        lblBuilder.setText("Builder Name");

        lblPhone.setText("Phone Number");

        lblAddress.setText("Address");

        txtBuilder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuilderActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Builder Details");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Backgrounds/silhouette-of-engineer-and-worker-man-team-technician-and-builders-construction-teamwork-cartoon-character-vector.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPhone)
                    .addComponent(lblBuilder, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtBuilder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAddress, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(315, 315, 315))
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(495, 495, 495)
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuilder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBuilder))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnAdd)
                .addGap(40, 40, 40)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtBuilderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuilderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuilderActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        String builderName = txtBuilder.getText().trim();
        String phoneNumber = txtPhone.getText().trim();
        String address = txtAddress.getText().trim();
        
        if (builderName.isEmpty() || phoneNumber.isEmpty() || address.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                "Please fill in all fields.",
                "Incomplete Information",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
          // Validate phone number format (10 digits only)
        if (!isValidPhoneNumber(phoneNumber)) {
            JOptionPane.showMessageDialog(this,
                "Please enter a valid 10-digit phone number.",
                "Invalid Phone Number",
                JOptionPane.WARNING_MESSAGE);
            return;
        }
        
       try {
            // Create a new builder user account instead of updating existing one
            createNewBuilderEntry(builderName, phoneNumber, address);
            
            JOptionPane.showMessageDialog(this,
                "Builder details added successfully!",
                "Success",
                JOptionPane.INFORMATION_MESSAGE);
            
            System.out.println("New builder added: " + builderName + ", " + phoneNumber + ", " + address);
            clearForm();
            
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,
                "Error adding builder details: " + e.getMessage(),
                "Error",
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Validate phone number - must be 10 digits only
     */
    private boolean isValidPhoneNumber(String phoneNumber) {
        // Remove any non-digit characters
        String digitsOnly = phoneNumber.replaceAll("\\D", "");
        
        // Check if it's exactly 10 digits
        return digitsOnly.length() == 10;
    }
    
    private void createNewBuilderEntry(String builderName, String phoneNumber, String address) {
        // Create a new Builder role with the provided details
        Builder newBuilder = new Builder(builderName, address, phoneNumber);
        
        // Create a unique username for this builder entry
        String uniqueUsername = "builder_" + System.currentTimeMillis();
        
        // Create a new UserAccount for this builder
    UserAccount newBuilderAccount = new UserAccount();
    newBuilderAccount.setUsername(uniqueUsername);
    newBuilderAccount.setPassword("default123"); // Default password
    newBuilderAccount.setName(builderName);
    newBuilderAccount.setRole(newBuilder);
        
        // Find or create BuilderOrganization
        BuilderOrganization builderOrg = findOrCreateBuilderOrganization();
        
        // Set the organization for the new account
        newBuilderAccount.setOrganization(builderOrg);
        
        // Add the new builder to the organization
        builderOrg.getUserAccountList().add(newBuilderAccount);
        
        // Add to UserAuthentication system
        UserAuthentication userAuth = UserAuthentication.getInstance();
        userAuth.getUserAccounts().add(newBuilderAccount);
        
        // Save changes to file
        saveChangesToFile();
        
        System.out.println("Created new builder entry with username: " + uniqueUsername);
    }
    
    private BuilderOrganization findOrCreateBuilderOrganization() {
        // Find existing BuilderOrganization
        for (Enterprise enterprise : ecosystem.getEnterpriseList()) {
            if (enterprise instanceof PropertyManagementEnterprise) {
                for (Organization org : enterprise.getOrganizationList()) {
                    if (org instanceof BuilderOrganization) {
                        return (BuilderOrganization) org;
                    }
                }
            }
        }
        
        // If no BuilderOrganization found, create one
        PropertyManagementEnterprise propertyEnterprise = null;
        for (Enterprise enterprise : ecosystem.getEnterpriseList()) {
            if (enterprise instanceof PropertyManagementEnterprise) {
                propertyEnterprise = (PropertyManagementEnterprise) enterprise;
                break;
            }
        }
        
        if (propertyEnterprise == null) {
            // Create PropertyManagementEnterprise if it doesn't exist
            propertyEnterprise = new PropertyManagementEnterprise("Default Property Management");
            ecosystem.addEnterprise(propertyEnterprise);
        }
        
        // Create new BuilderOrganization
        BuilderOrganization newBuilderOrg = new BuilderOrganization("Builder Organization", propertyEnterprise);
        propertyEnterprise.addOrganization(newBuilderOrg);
        
        return newBuilderOrg;
    }
    
    private void saveChangesToFile() {
        try {
            // Save ecosystem
            FileOutputStream fileOut = new FileOutputStream("ecosystem.ser");
            ObjectOutputStream out = new ObjectOutputStream(fileOut);
            out.writeObject(ecosystem);
            out.close();
            fileOut.close();
            
            // Save UserAuthentication
            UserAuthentication userAuth = UserAuthentication.getInstance();
            FileOutputStream userFileOut = new FileOutputStream("userauth.ser");
            ObjectOutputStream userOut = new ObjectOutputStream(userFileOut);
            userOut.writeObject(userAuth);
            userOut.close();
            userFileOut.close();
            
            System.out.println("Builder data saved successfully");
            
        } catch (IOException e) {
            e.printStackTrace();
            System.err.println("Error saving builder data: " + e.getMessage());
        }
        
        
        
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBuilder;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBuilder;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
